### ISSUE TITLE
Stex Not Working

### ISSUE THREAD

**Issue by hackingbeauty** [stellar/stellar-wallet#77]
The command "stex www --watch" does not work.  Firstly, the command cannot be found; however, even when prefacing the command with the path to the Stex executable I am receiving an error: 

./node_modules/stex/bin/stex www --watch

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at ChildProcess.<anonymous> (/Users/markmuskardin/code/javascript/stellar-wallet/node_modules/stex/node_modules/nodemon/lib/monitor/run.js:119:11)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

Any clue?

**Comment by thejollyrogers** [comment]
Looks like a problem with --watch. Will look into it. In the meantime try it without that flag.

**Comment by hackingbeauty** [comment]
Thank you, you are correct!  BTW, the README needs to be updated to indicate the path to the stex excecutable.
